import Groq from 'groq-sdk';
import fs from 'fs';

const WHISPER_MODEL = 'whisper-large-v3-turbo';
const ANALYSIS_MODEL = process.env.GROQ_ANALYSIS_MODEL || 'llama-3.1-8b-instant';

function getClient() {
  const apiKey = process.env.GROQ_API_KEY;
  if (!apiKey) {
    throw new Error('GROQ_API_KEY is not configured on the server');
  }
  return new Groq({ apiKey });
}

/**
 * @param {string} filePath
 * @param {string} originalName
 * @param {string} mimeType
 */
export async function transcribeAudio(filePath, originalName, mimeType) {
  const groq = getClient();
  const file = fs.createReadStream(filePath);

  const transcription = await groq.audio.transcriptions.create({
    file,
    model: WHISPER_MODEL,
    language: 'en',
    response_format: 'verbose_json',
    temperature: 0,
    prompt:
      'Breathing sounds, cough, wheeze, asthma symptoms. Medical respiratory audio.',
  });

  return transcription;
}

/**
 * @param {import('groq-sdk').default.Audio.Transcriptions.Transcription} transcription
 */
export async function analyzeTranscription(transcription) {
  const groq = getClient();

  const segmentSummary = (transcription.segments || [])
    .slice(0, 12)
    .map((s) => ({
      text: s.text,
      avg_logprob: s.avg_logprob,
      no_speech_prob: s.no_speech_prob,
      compression_ratio: s.compression_ratio,
    }));

  const completion = await groq.chat.completions.create({
    model: ANALYSIS_MODEL,
    temperature: 0.1,
    response_format: { type: 'json_object' },
    messages: [
      {
        role: 'system',
        content: `CRITICAL FIRST STEP: Analyze the transcription and segments to determine if the recording is a valid respiratory screening audio. A valid recording MUST contain actual respiratory sounds (breathing, coughing, gasping, sighing, or wheezing). If the recording is invalid (e.g. it contains pure coherent conversational talking, clear spoken words with no respiratory sounds, loud music, singing, or absolute silence), you MUST return the JSON with "invalid": true, "summary": "Invalid audio recording. Please upload a clear recording containing breathing, coughing, or wheezing.", "clinicalFindings": "Invalid audio recording. Please upload a clear recording containing breathing, coughing, or wheezing.", and set all other fields to default or empty values. Otherwise, set "invalid": false. If there is any respiratory sound (breathing, sighing, coughing, or wheezing) even if accompanied by background noise or transcription hallucinations, set "invalid": false.

You are a professional respiratory symptom screening assistant for AsthmaSense AI.
Your absolute #1 priority is to detect and analyze expiratory WHEEZING, chest tightness, whistling breathing, dry spasmodic coughs, or restricted airflow. You must check for wheezing first, above all other observations. Coughing, congestion, and other respiratory patterns are secondary.

CRITICAL CONTEXT FOR RAW RESPIRATORY RECORDINGS:
- The user is uploading raw recordings of their breathing, coughing, and wheezing. These audios usually contain ZERO spoken words.
- Do not assume breath or respiratory noises as spoken words since Whisper sometimes erroneously tries to transcribe breathing sounds.
- The transcription is generated by Whisper. When there is no speech, Whisper transcribes acoustic respiratory sounds into bracketed/parenthesised annotations.
- You MUST scan the transcript AND all segment texts for non-speech tokens such as:
  - "[coughing]", "[cough]", "[sighing]", "[breathing]", "[gasping]", "[sniffling]", "[whistling]", "(coughing)", "(sighing)", "(breathing)", "(whistling)", or similar annotations.
- Any presence of these annotations means active respiratory sounds were detected! You must analyze them deeply.
- Expiratory wheezing is clinically characterized by a high-pitched, musical whistling, whistling rattling, or prolonged/forced exhalation.
- If exhalation is heavy, restricted, whistled, or accompanied by spasmodic coughing, wheezing is highly likely to be present!
- If heavy respiratory cycles (such as heavy, labored, deep, loud, or rapid breathing cycles) are present or described in the transcript/segments, you MUST classify this as wheezing (set wheezingDetected as "Yes" and riskLevel as "High").

Acoustic Metadata Deep-Dive:
- Analyze the segments array and segment-level metrics (no_speech_prob, avg_logprob, compression_ratio):
  - A high "no_speech_prob" (e.g., > 0.4) with text like "[coughing]", "[breathing]" or empty segments indicates a raw, non-speech breathing recording.
  - Pay close attention to exhalation or coughing sequences. If exhalations are noisy or accompanied by whistling/coughing tokens, this suggests restricted airflow.
  - Err on the side of caution! If any expiratory wheezing, exhalation whistling, whistling breathing, or heavy respiratory cycles are detected, you MUST immediately classify wheezingDetected as "Yes" and riskLevel as "High" to ensure patient safety!

    Respond ONLY with valid JSON in this exact shape:
    {
      "invalid": boolean,
      "wheezingDetected": "Yes" | "No",
      "riskLevel": "Low" | "Moderate" | "High",
      "summary": "one short sentence for the user describing the main acoustic finding",
      "clinicalFindings": "an extremely detailed and comprehensive medical analysis describing FIRST your high-fidelity expiratory wheezing and restricted airflow observations, followed by secondary observations like cough frequency, spacing, exhalation length, sound depth (dry/wet spasmodic), acoustic signals, and potential physiological implications for airway resistance.",
      "confidence": "Low" | "Medium" | "High",
      "rr": "14 bpm" | "16 bpm" | "18 bpm" | "20 bpm" | "22 bpm",
      "pattern": "None detected" | "Mild cough · X events" | "Heavy cough · X events" | "Wheezing exhalation · X events",
      "regularity": "95%" | "90%" | "84%" | "72%",
      "recommendedExercise": "box" | "belly" | "pursed" | "diaphragm" | "none",
      "recommendations": [string, string, string],
      "foodsToEat": [string, string, string],
      "foodsToAvoid": [string, string, string]
    }

    Rules:
    - invalid: Set to true ONLY if the audio transcription contains clear coherent conversational talking/speech, music, singing, or absolute silence with absolutely no audible respiratory cycles. If there are breathing cycles, sighing, coughing, or wheezing (even if faint or noisy or if Whisper misinterprets them as short words), set invalid to false.
    - wheezingDetected: Set to "Yes" if high-pitched whistling exhalations, spasmodic dry coughs, whistled breathing, asthmatic rattles, restricted expiratory cycles, OR heavy, labored, deep, or loud respiratory cycles are identified in the audio transcript or segments.
    - riskLevel:
      - High = if expiratory wheezing is detected, OR if severe spasmodic coughing (e.g. 4 or more distinct cough events transcribed or in segments), heavily restricted or prolonged exhalation, gasping breathing, or obvious respiratory distress is identified.
      - Moderate = mild to moderate coughing (e.g. 1 to 3 occasional coughs or throat clears), mild congestion, or forced exhalation (with zero active wheeze).
      - Low = normal, clear, uninhibited respiratory breathing cycles with no wheeze or active coughing.
    - pattern:
      - If coughing is detected (e.g. transcription contains [cough], [coughing]), set this field to "Mild cough · X events" (for 1 to 3 occasional events) or "Heavy cough · X events" (for 4 or more events), substituting X with the count of cough events.
      - If no coughing is detected (even if expiratory wheezing, whistling, or asthmatic rattling is prominent), set this field to "None detected".
    - regularity: Standard breath/cough cycle consistency based on segment logs (Low risk is usually 90%-96%, Moderate is 80%-89%, High risk is under 80%).
    - recommendedExercise: Match the respiratory analysis to one of these 4 supported exercises:
      - "box" (Box Breathing): best for elevated heart rate, respiratory control, panic, or hyperventilation.
      - "belly" (Deep Belly): best for shallow breathing, standard calming, or chest tightness.
      - "pursed" (Pursed Lip): best for shortness of breath, active asthmatic wheezing, COPD, or easing air trapping.
      - "diaphragm" (Diaphragmatic Reset): best for tense muscles or post-flare recovery.
      If none of these is suitable, set to "none".
    - recommendations: A list of exactly 3 actionable, highly helpful clinical advice bullet points.
    - foodsToEat: Exactly 3 highly useful dietary food recommendations that are clinically beneficial for the current asthmatic status (e.g. warm fluids, ginger, antioxidant-rich fruits/veggies).
    - foodsToAvoid: Exactly 3 specific dietary foods/drinks that can trigger symptoms, provoke reflux, or cause bronchial constriction (e.g. ice-cold beverages, sulfited dried fruits, processed allergens).
    - This is screening only, not a medical diagnosis.`,
      },
      {
        role: 'user',
        content: JSON.stringify({
          transcript: transcription.text || '',
          duration: transcription.duration,
          language: transcription.language,
          segments: segmentSummary,
        }),
      },
    ],
  });

  const raw = completion.choices[0]?.message?.content || '{}';
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch {
    parsed = {
      invalid: false,
      wheezingDetected: 'No',
      riskLevel: 'Moderate',
      summary: 'Analysis completed with limited confidence.',
      clinicalFindings: 'Acoustic screening completed with mild interference. High-pitched signals could not be fully cataloged due to signal noise, but a shallow exhalation pattern is present.',
      confidence: 'Low',
      rr: '16 bpm',
      pattern: 'None detected',
      regularity: '90%',
      recommendedExercise: 'none',
      recommendations: ['Practice deep breathing regularly.', 'Avoid allergens and dynamic physical strain.', 'Monitor respiratory changes closely.'],
      foodsToEat: ['Warm ginger tea', 'Omega-3 rich foods (salmon)', 'Vitamin C fruits (oranges)'],
      foodsToAvoid: ['Ice-cold water', 'Sulfited dried fruits', 'Highly processed snacks']
    };
  }

  return {
    invalid: parsed.invalid === true || parsed.invalid === 'true',
    wheezingDetected: normalizeYesNo(parsed.wheezingDetected),
    riskLevel: normalizeRisk(parsed.riskLevel),
    summary: String(parsed.summary || 'Analysis complete.'),
    clinicalFindings: String(parsed.clinicalFindings || parsed.summary || 'Acoustic screening completed successfully.'),
    confidence: String(parsed.confidence || 'Medium'),
    transcript: transcription.text || '',
    rr: String(parsed.rr || (parsed.wheezingDetected === 'Yes' ? '20 bpm' : '15 bpm')),
    pattern: String(parsed.pattern || 'None detected'),
    regularity: String(parsed.regularity || '92%'),
    recommendedExercise: String(parsed.recommendedExercise || 'none').toLowerCase(),
    recommendations: Array.isArray(parsed.recommendations) ? parsed.recommendations : ['Practice deep breathing regularly.', 'Avoid allergens and dynamic physical strain.', 'Monitor respiratory changes closely.'],
    foodsToEat: Array.isArray(parsed.foodsToEat) ? parsed.foodsToEat : ['Warm ginger tea', 'Omega-3 rich foods (salmon)', 'Vitamin C fruits (oranges)'],
    foodsToAvoid: Array.isArray(parsed.foodsToAvoid) ? parsed.foodsToAvoid : ['Ice-cold water', 'Sulfited dried fruits', 'Highly processed snacks']
  };
}

function normalizeYesNo(value) {
  const v = String(value || '').toLowerCase();
  return v === 'yes' || v === 'true' ? 'Yes' : 'No';
}

function normalizeRisk(value) {
  const v = String(value || '').toLowerCase();
  if (v.includes('high')) return 'High';
  if (v.includes('moderate') || v.includes('medium')) return 'Moderate';
  return 'Low';
}

export async function generateClinicalReport(data, userProfile = {}) {
  const groq = getClient();
  
  // Format the baseline user profile if available
  let profileBaseline = '';
  if (userProfile && userProfile.hasCompletedOnboarding) {
    profileBaseline = `
[PATIENT BASELINE CLINICAL INFORMATION]
- Age: ${userProfile.age || 'N/A'} years old
- Asthma Severity: ${userProfile.severity || 'N/A'}
- Primary Environmental/Activity Triggers: ${userProfile.triggers && userProfile.triggers.length > 0 ? userProfile.triggers.join(', ') : 'N/A'}
- Prescribed Rescue Medication/Inhaler: ${userProfile.inhaler || 'N/A'}
- Baseline Symptom Frequency: ${userProfile.frequency || 'N/A'}
`;
  }

  const completion = await groq.chat.completions.create({
    model: ANALYSIS_MODEL,
    temperature: 0.2,
    response_format: { type: 'json_object' },
    messages: [
      {
        role: 'system',
        content: `You are a professional pulmonologist and respiratory care specialist.
Analyze the patient's health tracking records (symptom logs, AI breathing/cough audio analyses, and completed breathing exercises) over the tracked period, tailoring your assessment specifically to their clinical baseline.
${profileBaseline}
Respond ONLY with a valid JSON object in this exact shape:
{
  "clinicalSummary": "Professional medical summary of patient's current status and progress.",
  "triggerAnalysis": "Clinical analysis of logged triggers (pollen, dust, etc.) and potential environmental correlation.",
  "complianceEvaluation": "Pulmonary evaluation of breathing exercises completed and their impact on symptoms.",
  "actionPlan": [
    "Pulmonary action item 1",
    "Pulmonary action item 2",
    "Pulmonary action item 3"
  ]
}
Maintain a highly clinical, professional, encouraging, and precise tone. Identify any warning signs or positive trends.`
      },
      {
        role: 'user',
        content: JSON.stringify(data)
      }
    ]
  });

  const raw = completion.choices[0]?.message?.content || '{}';
  try {
    return JSON.parse(raw);
  } catch {
    return {
      clinicalSummary: "Unable to generate clinical summary.",
      triggerAnalysis: "Unable to analyze triggers.",
      complianceEvaluation: "Unable to evaluate breathing compliance.",
      actionPlan: [
        "Maintain prescribed inhaler schedule.",
        "Avoid known allergens and trigger environments.",
        "Log symptoms daily for clinical insight."
      ]
    };
  }
}
